### ISSUE TITLE
MinLog crashes without `serializeTime` serializer

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/minlog#13]
In the minimal setup like

```
let {
  MinLog,
  logToConsole
} = require('./src/index');

let logger = new MinLog({
  listeners: [
    logToConsole({
      level: 'INFO'
    })
  ],
  serializers: []
});
logger.info('test');
```

   crashes with
```
(node:75745) UnhandledPromiseRejectionWarning: TypeError: (0 , _moment.default)(
...).utcOffset(...).toISOString is not a function
    at Object.toISOString [as serialize] (/Users/isao/code/github/TobiiPro/minlo
g/src/listeners/log-to-console.js:56:73)
    at /Users/isao/code/github/TobiiPro/minlog/src/listeners/log-to-console.js:2
02:9
    at MinLog.listener [as log] (/Users/isao/code/github/TobiiPro/minlog/src/min
log.js:142:13)
    at apply (/Users/isao/code/github/TobiiPro/minlog/node_modules/lodash/lodash
.js:478:17)
    at MinLog.wrapper [as info] (/Users/isao/code/github/TobiiPro/minlog/node_mo
dules/lodash/lodash.js:5323:16)
    at Object.info (/Users/isao/code/github/TobiiPro/minlog/test.js:16:8)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (/Users/isao/code/github/TobiiPro/minlog/node_modules/pir
ates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .js] (/Users/isao/code/github/TobiiPro/minlog/node_m
odules/pirates/lib/index.js:104:7)
```

**Comment by andreineculau** [comment]
yes, because log-to-console listener is dependent on the time serializer.
I don't see it particularly bad that listeners need some serializers to work.

suggestions?

**Comment by IanSavchenko** [comment]
Not to use moment at all and use default Date serializer without any dependencies. Related to #14

**Comment by andreineculau** [comment]
that is unrelated. the "problem" is that the listener expects time to be formatted (serialized) i.e. expected `entry._time.stamp`

changing by what it is serialized (moment or date) is irrelevant.

**Comment by andreineculau** [comment]
I pushed 075e51c9 - because that's how I was imagining the console logger (but I forgot a 'true' argument when calling 'toISOString')

Related to #14, I also introduced duration-handling with trackTime. How do you suggest that to be solved, if we remove moment&similar and go back to built-in Date? A. just don't B. find a replacement for human durations C. ?

**Comment by IanSavchenko** [comment]
Well, that's not immediately obvious at all.
